language: c
compiler: gcc
addons:
  apt:
    packages:
    - texlive-latex-base
    - texlive-latex-extra
    - pgf
    - ghostscript
script:
  - make
notifications:
  email:
    recipients:
      - mail@ghorbanzade.com
    on_success: change
    on_failure: always
