language: java
sudo: false
addons:
  apt:
    packages:
    - texlive-latex-base
jdk:
  - openjdk7
  - oraclejdk8
before_install:
  - ant init-ivy
install:
  - ant resolve
script:
  - make clean
  - make
notifications:
  email:
    recipients:
      - mail@ghorbanzade.com
    on_success: change
    on_failure: always
